/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateSampleEntityArgs } from "./CreateSampleEntityArgs";
import { UpdateSampleEntityArgs } from "./UpdateSampleEntityArgs";
import { DeleteSampleEntityArgs } from "./DeleteSampleEntityArgs";
import { SampleEntityFindManyArgs } from "./SampleEntityFindManyArgs";
import { SampleEntityFindUniqueArgs } from "./SampleEntityFindUniqueArgs";
import { SampleEntity } from "./SampleEntity";
import { SampleEntityService } from "../sampleEntity.service";

@graphql.Resolver(() => SampleEntity)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class SampleEntityResolverBase {
  constructor(
    protected readonly service: SampleEntityService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SampleEntity",
    action: "read",
    possession: "any",
  })
  async _sampleEntitiesMeta(
    @graphql.Args() args: SampleEntityFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [SampleEntity])
  @nestAccessControl.UseRoles({
    resource: "SampleEntity",
    action: "read",
    possession: "any",
  })
  async sampleEntities(
    @graphql.Args() args: SampleEntityFindManyArgs
  ): Promise<SampleEntity[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => SampleEntity, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SampleEntity",
    action: "read",
    possession: "own",
  })
  async sampleEntity(
    @graphql.Args() args: SampleEntityFindUniqueArgs
  ): Promise<SampleEntity | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SampleEntity)
  @nestAccessControl.UseRoles({
    resource: "SampleEntity",
    action: "create",
    possession: "any",
  })
  async createSampleEntity(
    @graphql.Args() args: CreateSampleEntityArgs
  ): Promise<SampleEntity> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SampleEntity)
  @nestAccessControl.UseRoles({
    resource: "SampleEntity",
    action: "update",
    possession: "any",
  })
  async updateSampleEntity(
    @graphql.Args() args: UpdateSampleEntityArgs
  ): Promise<SampleEntity | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SampleEntity)
  @nestAccessControl.UseRoles({
    resource: "SampleEntity",
    action: "delete",
    possession: "any",
  })
  async deleteSampleEntity(
    @graphql.Args() args: DeleteSampleEntityArgs
  ): Promise<SampleEntity | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
